/**********************************************************************
 * Extern for stoch
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var stoch = {
  "poissP": function () {},
  "GBM": function () {},
  "DTMC": function () {},
  "collate": function () {},
  "CTMC": function () {},
  "sample": function () {},
  "exp": function () {},
  "pareto": function () {},
  "hist": function () {},
  "norm": function () {},
  "brown": function () {}
};
/**********************************************************************
 * End Generated Extern for stoch
/**********************************************************************/